spring:
  datasource:
    url: jdbc:sqlite:prod.sqlite
    driver-class-name: org.sqlite.JDBC
  # jpa 설청
  jpa:
    hibernate:
      # 테이블을 만들려고 하는데, 이미 있으면 제거(DROP)하고 다시 만든다
      ddl-auto: update #spring.jpa.hibernate.ddl-auto=create
    #
    database-platform: org.hibernate.community.dialect.SQLiteDialect

